### ISSUE TITLE
Unable to find users by full name

### ISSUE THREAD

**Issue by ghost** [intelliants/subrion-plugin-privatemessages#2]
When composing new message, it's possible to find addressee by username only.

It's often inconvenient as it might be looked for using full name as well.

**Comment by vbezruchkin** [comment]
> $stmt = '(`username` LIKE :name OR `fullname` LIKE :name) AND `status` = :status AND `id` != :id ORDER BY `username` ASC';

Looks like there is a condition, and it's actually working. The issue is that typeahead does not display this correctly.

We need to improve typeahead component to separate title & real value to avoid extra parsing.

**Comment by Frozenpath** [comment]
added finder users by full name
